### ISSUE TITLE
Expression Missing SQL Error

### ISSUE THREAD

**Issue by iversond** [UMN-PeopleSoft/IBMonitorService#23]
When setting up a basic IB Monitor (1 database, only default monitoring), there is a SQL syntax error in the resulting monitoring SQL. The SQL is missing single quotes inside the parentheses for `NOT IN ()`.

Example SQL Error:

```sql
Select /*+ Index(PSAPMSGPUBHDR PSCPSAPMSGPUBHDR) */ IBTRANSACTIONID From PSADM.PSAPMSGPUBHDR Where PUBSTATUS in (0,5,6) and IBTRANSACTIONID not in ();
00936. 00000 -  "missing expression"
*Cause:    
*Action:
Error at Line: 37 Column: 149
```

Here is the configuration for the setup:

```yaml
---
root:
  emailUser: ibmonitor@domain.com
  emailPassword: 
  emailReplyTo: ibmonitor@domain.com
  emailHost: mail.domain.com
  emailPort: '25'
  onCallFile: 'c:/psadmin/oncallfile'
  debugMode: 'OFF'
  dbType: Oracle
  database:
  - databaseName: FDEV
    host: fdev:1521/FDEV.domain.com
    user: MONITOR
    password: <password>
    dbSchema: SYSADM
    sleepTime: '5'
    defaultMonitorTime: '0'
    defaultStatusToCheck: '0,5,6'
    defaultRetryCount: '0'
    defaultNotifyTo: me@domain.com
    defaultNotifyCC: ''
    defaultNotifyInterval: '60'
    downTimeStartDay: '1'
    downTimeStart: '6:00'
    downTimeEndDay: '1'
    downTimeEnd: '12:00'
    downTimeFrequency: '7'
    defaultNotifyIntervalOffHours: '720'
    startTimeOffHours: '17:00'
    endTimeOffHours: '7:00'
    domainStatus: 'OFF'
```
